sudo: false
language: java
jdk:
  - openjdk11

script:
  - mvn clean install -Pgenerate-javadoc

after_success:
  - mvn jacoco:prepare-agent test jacoco:report coveralls:report

cache:
  directories:
    - $HOME/.m2
